apiVersion: v2
name: nukkit
version: 0.1.0
description: A Helm chart for Nukkit
type: application
keywords:
  - minecraft
home: "https://github.com/flaccid/container-nukkit"
sources:
  - "https://github.com/flaccid/container-nukkit"
maintainers:
  - name: Chris Fordham
    email: chris@fordham.id.au
icon: "https://github.com/CloudburstMC/Nukkit/raw/master/.github/images/banner.png"
appVersion: 0.1.0
